README.md, lib/bootleg/tasks/update.exs, lib/mix/tasks/update.ex, test/bootleg_functional_test.exs
=> Add `mix bootleg.update` command

README.md, lib/bootleg/config.ex, lib/bootleg/ssh.ex, test/bootleg/config_functional_test.exs, test/bootleg/config_test.exs, test/bootleg/ssh_test.exs, test/strategies/build/distillery_test.exs
=> Add special `:all` role.

README.md, lib/mix/tasks/init.ex, test/bootleg_functional_test.exs, test/fixtures/n00b/.gitignore, test/fixtures/n00b/config/config.exs, test/fixtures/n00b/lib/n00b.ex, test/fixtures/n00b/mix.exs
=> Add bootleg.init Mix task.

README.md, lib/mix/tasks/invoke.ex, lib/ui.ex, test/bootleg/tasks/invoke_task_test.exs, test/ui_test.exs
=> Add bootleg.invoke mix command.

README.md, lib/bootleg/config.ex, lib/bootleg/ssh.ex, test/bootleg/config_test.exs, test/bootleg/ssh_functional_test.exs, test/strategies/build/distillery_test.exs
=> Add filtering to `remote`.

lib/bootleg/config.ex, lib/bootleg/ssh.ex, test/bootleg/config_functional_test.exs, test/bootleg/config_test.exs, test/bootleg/ssh_test.exs, test/strategies/build/distillery_test.exs
=> Fix host attribute filtering in remote/3.

lib/bootleg/config.ex, lib/bootleg/ssh.ex, test/bootleg/config_functional_test.exs, test/bootleg/config_test.exs
=> Add `upload` DSL verb.

README.md, lib/bootleg/tasks/build.exs, lib/strategies/build/distillery.ex, test/strategies/build/distillery_functional_test.exs
=> Clean workspace before building.

README.md, lib/bootleg/config.ex, lib/bootleg/config/agent.ex, lib/bootleg/mix_task.ex, lib/bootleg/tasks.ex, lib/mix/tasks/init.ex, lib/ui.ex, test/bootleg/config/agent_test.exs, test/bootleg/config_test.exs, test/bootleg/tasks_functional_test.exs, test/bootleg_functional_test.exs, test/fixtures/bootstraps/config/deploy/production.exs, test/fixtures/build_me/config/deploy/production.exs, test/fixtures/task_consumer/config/deploy/production.exs, test/support/docker/Dockerfile, test/support/functional_case.ex, test/support/test_case.ex, test/ui_test.exs
=> Add support for multiple bootleg environments.

README.md, lib/bootleg/tasks/build.exs, test/strategies/build/distillery_functional_test.exs
=> Add `clean_locations` config option.

README.md
=> Remove reference to local only builds.

lib/bootleg/config.ex, lib/bootleg/config/agent.ex, lib/bootleg/ssh.ex, test/bootleg/ssh_test.exs
=> Add quiet_mode to supported SSH options.

mix.exs
=> Add homepage link and improve source code linking.

lib/bootleg/ssh.ex, lib/ui.ex, test/bootleg/ssh_functional_test.exs, test/ui_test.exs
=> Ensure only whole lines of SSH output are emitted.

README.md, lib/bootleg/config.ex, lib/bootleg/ssh.ex, test/bootleg/ssh_functional_test.exs, test/support/docker/Dockerfile
=> Add `REPLACE_OS_VARS` support.

lib/bootleg/config.ex, lib/bootleg/ssh.ex, test/bootleg/config_functional_test.exs, test/bootleg/config_test.exs
=> Add `download/3` DSL verb.

lib/bootleg/tasks/build.exs, lib/strategies/build/distillery.ex
=> Update compile task to get deps

lib/bootleg/ssh.ex, mix.lock, test/bootleg/ssh_test.exs
Pass related ssh options on to key_cb_private
=> Correct behavior of silently_accept_hosts

lib/bootleg/ssh.ex
=> Add support for home directory paths

README.md, lib/bootleg/config.ex, lib/bootleg/ssh.ex, lib/bootleg/task.ex, test/bootleg/config_functional_test.exs, test/bootleg/config_test.exs, test/bootleg/ssh_functional_test.exs
=> Add :env option when defining roles

lib/bootleg/ssh.ex, test/bootleg/ssh_functional_test.exs
=> Set BOOTLEG_ENV environment variable for all remote commands

README.md
=> Document the config/1 and config/2 macros

README.md
=> Use identity in role definition examples

README.md, lib/bootleg/tasks/build.exs, test/bootleg/tasks/build_task_functional_test.exs
=> Rename local_build option to build_type

test/bootleg/tasks/build_task_functional_test.exs
=> Add assertions to build functional tests

README.md, script/ci/prepare.sh, test/fixtures/build_me/mix.exs, test/fixtures/n00b/mix.exs, test/fixtures/task_consumer/mix.exs, test/support/docker/Dockerfile, test/support/functional_case.ex
also clean up dockerfile for test apps (pin base image version, remove extraneous package repo)
=> upgrade distillery, elixir, erlang

lib/bootleg/tasks/build/remote.exs
=> WIP - Use ex_path in remote builds w/ release_workspace set

lib/bootleg/dsl.ex, test/bootleg/dsl_test.exs
=> Allow the redefinition of tasks to suppress warnings

.credo.exs, mix.lock
=> Update credo configuration

index.html
Update Distillery and Bootleg versions in github pages. Closes #304.
=> Update github pages versions

mix.exs
sshkit got updated to fix some [deprecation warnings](https://github.com/bitcrowd/sshkit.ex/issues/147).
Please delete options that are not relevant.
**By submitting this PR, you agree to the following statement, please read before submission!**
I certify that I own, and have sufficient rights to contribute, all source code and
related material intended to be compiled or integrated with the source code for Bootleg
(the "Contribution"). My Contribution is licensed under the MIT License.
NOTE: If you submit a PR and remove the statement above, your PR will be rejected. For your PR to be
considered, it must contain your agreement to license under the MIT license.
=> Updated SSHkit
